version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: codespace-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: codespace_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - codespace-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: codespace-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 5000
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD:-password123}@mongodb:27017/codespace_db?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - codespace-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: codespace-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - codespace-network

  # Ollama Service for AI Code Analysis
  ollama:
    image: ollama/ollama:latest
    container_name: codespace-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - codespace-network
    command: serve

  # Nginx Reverse Proxy (Optional for production)
  nginx:
    image: nginx:alpine
    container_name: codespace-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - codespace-network
    profiles:
      - production

volumes:
  mongodb_data:
  ollama_data:

networks:
  codespace-network:
    driver: bridge